### PR TITLE
fix: support multiple useSWRInfinite hooks in a page

### LINKED ISSUE #976: useSwrInfinite order of calling hooks and setSize matters
# Bug report

## Description / Observed Behavior

Let's say there are 2 components, A and B.
A and B are using custom hook which is returning useSwrInfinite props.
One of them, let's say B, is also setting size using setSize.

If you have:
```
return (
  <>
    <A />
    <B /> // setting size
  </>
)
```
setSize will increase size variable, but for some reason useSwrInfinite will not make a new fetch request for new page.

But if you switch order in which component setting size is rendered before:
```
return (
  <>
    <B /> // setting size
    <A />
  </>
)
```
then all works as intended.

## Expected Behavior

I should be able to set size anywhere and all my components using useSwrInfinite (and same key of course) should update.
Also data fetching should occur.

## Repro Steps / Code Example

https://codesandbox.io/s/lucid-frost-srix1?file=/src/App.js

```
import { useSWRInfinite } from "swr";

const useHook = () => {
  const { data, size, setSize } = useSWRInfinite(
    (pageIndex) => [`abc-${pageIndex}`, pageIndex],
    async (key, pageIndex) => {
      const response = await fetch(
        `https://api.github.com/repos/reactjs/react-a11y/issues?per_page=6&page=${pageIndex + 1}`
      )
        .then((response) => response.json())
        .then((data) => data);

      return response;
    }
  );

  return {
    data,
    size,
    setSize
  };
};

const A = () => {
  const { data, size, setSize } = useHook();

  return (
    <div>
      <div>
        {data &&
          data.map((item) =>
            item.map((it) => <div key={it.id}>{it.title}</div>)
          )}
      </div>
      <button onClick={() => setSize(size + 1)}>new page</button>
    </div>
  );
};

const B = () => {
  const { data } = useHook();
  console.log(data);

  return <div>B</div>;
};

export default function App() {
  return (
    <div>
      <B />
      <A />
      {/* 
      // this works where A is before B
      <A />
      <B />
      */}
    </div>
  );
}
```

## Additional Context

React 17.0.1
SWR 0.4.2

### PR DESCRIPTION
**Pull request by koba04**
fixes #976
This PR fixes issues caused by using multiple `useSWRInfinite` on a page.
You can see the issues in the following link (v0.42).

- **v0.42**: https://codesandbox.io/s/swr-basic-forked-nw6z4
- **THIS PR**: https://codesandbox.io/s/swr-basic-forked-uo7r0

This PR also fixes #976.
https://codesandbox.io/s/swr-basic-forked-mbx6y

I guess this is a naive implementation and would change some behaviors of `useSWRInfinite`, so it should be merged carefully.

### CODE REVIEW

**Comment by koba04** [comment]
Why has the CodeSandbox build been failed?

> ModuleNotFoundError
Could not find module in path: 'swr' relative to '/src/App.js'

**Comment by promer94** [comment]
After #995 codesandbox ci seems broken 🥲 .  I am working on it

**Comment by promer94** [comment]
https://github.com/vercel/swr/blob/66aaefddeaf3f11ae80b7480482769521bd364da/tsconfig.json#L25-L28 

Adding new item in include filed would change the esm directory structure 🙈
should be fixed in #1011

**Comment by koba04** [comment]
@promer94 I got it, thank you!

**Comment by koba04** [comment]
I've confirmed that this doesn't work, so I'll investigate more.
https://codesandbox.io/s/swr-basic-forked-s0dgl?file=/src/App.js

File: src/use-swr-infinite.ts [hunk 1]
```diff
@@ -67,7 +67,8 @@ function useSWRInfinite<Data = any, Error = any>(
   )
   let {
     initialSize = 1,
-    revalidateAll = false,
+    // should revalidate pages when a refresh timer is invoked
+    revalidateAll = !!config.refreshInterval,
```
Comment (shuding) [inline src/use-swr-infinite.ts:71]: I'm not sure if we want to do this. Normally the `useSWRInfinite` API scenarios are cursor based, and in those cases we only need to revalidate the first page when polling because updates will likely happen in the newest page, and it will be too expensive to always revalidate all. Maybe it's better to let the user to enable it explicitly.

File: src/use-swr-infinite.ts [hunk 2]
```diff
@@ -117,10 +118,11 @@ function useSWRInfinite<Data = any, Error = any>(
 
   // keep the data inside a ref
   const dataRef = useRef<Data[]>()
+  const lastFetchedDataRef = useRef<Data[]>()
 
   // actual swr of all pages
   const swr = useSWR<Data[], Error>(
-    firstPageKey ? ['many', firstPageKey] : null,
+    firstPageKey ? ['many', firstPageKey, pageCountRef.current] : null,
```
Comment (shuding) [inline src/use-swr-infinite.ts:125]: I don't think we should change the key here. It's OK to update both lists when clicking "new page" in the sandbox you shared, since the data (including all pages) is bound to the key.

Comment (koba04) [reply src/use-swr-infinite.ts:125]: @shuding Thank you for your feedback!

> It's OK to update both lists when clicking "new page"

I misunderstood the expected behavior. In that case, should SWR manage the page count in the cache rather than a ref in the component? Because the ref is stored in each component, so it seems to cause inconsistency between components.

```
A1 -> pageCount: 1, data: 1-1, 1-2, 1-3
A2 -> pageCount: 1, data: 1-1, 1-2, 1-3

A1 changes pageCount to 2

A1 -> pageCount: 2, data: 1-1, 1-2, 1-3, 2-1, 2-2, 2-3
A2 -> pageCount: 1, data: 1-1, 1-2, 1-3, 2-1, 2-2, 2-3 # pageCount should be 2

```

Comment (shuding) [reply src/use-swr-infinite.ts:125]: Yeah I think so! The page count is current kept in the cache:

```js
pageCountCacheKey = 'len@' + firstPageKey
```

But we also used a ref to handle it too, which brings the inconsistency I believe. Maybe we should only use the cached page count to manage that, and trigger a revalidation when it changes.

Comment (koba04) [reply src/use-swr-infinite.ts:125]: To support `persistSize: true`, we might have to keep something as a ref to persist the size between different keys.
https://github.com/vercel/swr/pull/490

Comment (shuding) [reply src/use-swr-infinite.ts:107]: Ah that's true, good catch! 👍 It makes things a little bit complicated here although.

**Comment by koba04** [comment]
all tests now have been passed 🎉 But I have to refactor the implementation to get this merged.

File: src/use-swr-infinite.ts (hunk 2 above)
Comment (koba04) [reply src/use-swr-infinite.ts]: I've addressed this.

File: src/use-swr-infinite.ts [hunk 3]
```diff
@@ -185,23 +178,37 @@ function useSWRInfinite<Data = any, Error = any>(
...
-        pageCountRef.current = arg(pageCountRef.current)
+        cache.set(pageCountCacheKey, arg(resolvePageCount()))
+        lastPageCountRef.current = arg(resolvePageCount())
       } else if (typeof arg === 'number') {
-        pageCountRef.current = arg
+        cache.set(pageCountCacheKey, arg)
+        lastPageCountRef.current = arg
       }
-      cache.set(pageCountCacheKey, pageCountRef.current)
-      rerender(v => !v)
```
Comment (koba04) [inline src/use-swr-infinite.ts:197]: I didn't catch why the `rerender` was required, so please let me know if SWR still need to have it.

Comment (shuding) [reply src/use-swr-infinite.ts:200]: That's because we updated the size by changing a ref: `pageCountRef.current = arg`, which doesn't trigger a re-render (although it could be triggered by `mutate`, that might take a while). But the user needs to get the feedback, for example:

```js
const { size, setSize } = useSWRInfinite(...)

console.log(size)

return <button onClick={() => setSize(size + 1)}>inc</button>
```

When you click the button, it might not output the new page size.

Comment (koba04) [reply src/use-swr-infinite.ts:200]: Thank you!
In this case, `mutate(v => v)` seems to be enough to trigger a re-render.
https://codesandbox.io/s/swr-infinite-mv98u?file=/src/App.js
The CodeSandbox updates the `size` immediately.

File: src/use-swr-infinite.ts [hunk 4]
```diff
@@ -188,23 +180,38 @@ function useSWRInfinite<Data = any, Error = any>(
...
+  useEffect(() => {
+    if (!didMountRef.current) {
+      didMountRef.current = true
+      return
+    }
+    cache.set(
+      pageCountCacheKey,
+      persistSize ? lastPageCountRef.current : initialSize
+    )
+    mutate(v => v)
```
[the remark this answers is not in the document]
Comment (koba04) [reply src/use-swr-infinite.ts]: Fixed as 6659aaa

**Comment by koba04** [comment]
I wanted to re-use `useIsomorphicLayoutEffect` in `useSWRInfinite`, but I didn't want to expose it from `use-swr`, so I've moved it to `web-presets` and imported it.

**Comment by koba04** [comment]
This is now ready for review again 🚀

File: src/libs/web-preset.ts [hunk 5]
```diff
@@ -51,10 +53,28 @@ const registerOnReconnect = (cb: () => void) => {
...
 export default {
   isOnline,
   isDocumentVisible,
   fetcher,
   registerOnFocus,
-  registerOnReconnect
+  registerOnReconnect,
+  rAF,
+  useIsomorphicLayoutEffect,
+  IS_SERVER
```
Comment (shuding) [inline src/libs/web-preset.ts:79]: I think these belong to web-preset, but shouldn't be included in `defaultConfig` because they are not "config", and we don't want to expose them to the context.

Comment (koba04) [reply src/libs/web-preset.ts:79]: @shuding Thank you for your feedback! That makes sense 👍  What about exposing them as an external file like `env.ts`? Should I copy and have them as duplicated?

Comment (shuding) [reply src/libs/web-preset.ts:79]: > What about exposing them as an external file like env.ts?

Yeah that’s a good idea 👍

Comment (koba04) [reply src/libs/web-preset.ts]: Thank you! I've fixed it.

**Review by shuding — APPROVED** [review]
This fix is neat, thank you!

**Comment by koba04** [comment]
Thank you for your help! 🎉
