### PR TITLE
types: conditional swr response

### LINKED ISSUE #1410: typeof 'data' is always optional even with 'fallbackData' provided.
# Bug report

## Description / Observed Behavior
type of `data`

## Expected Behavior
type of `data` should be `Data`(not `Data | undefined`) if `fallbackData` has provided in type `Data`.

## Repro Steps / Code Example
```typescript
const { data } = useSWR<string>('my-key', {
  fallbackData: 'hello world',
});
```
image

SWR version. 
1.0.0

### PR DESCRIPTION
**Pull request by huozhi**
Resolves #1410

When `fallbackData` is specified for the swr hook, then:
 * it should match the `Data` type returning from `Fetcher`
 * swr hook should always return a fulfilled `data`
 * the `isLoading` always should be `false`

When `suspense` is specified for the swr hook, then:
 * swr hook should always return a fulfilled `data`
 * the `isLoading` always should be `false`

image

### CODE REVIEW

**Comment by promer94** [comment]
I like the idea. 
But i think we could achieve this without introducing another generic.  I opened #2306 as an possible alternaive

**Comment by huozhi** [comment]
> I like the idea. But i think we could achieve this without introducing another generic. I opened #2306 as an possible alternaive

but it introduces more typing reloading for the hook, so we gonna manage more reloadings. For the new genertic type this PR only introduced one, but #2306 have more new interface with genertics need to manage?

File: _internal/types.ts [hunk 1]
```diff
@@ -21,10 +21,18 @@ export type Fetcher<
   ? (arg: Arg) => FetcherResponse<Data>
   : SWRKey extends null | undefined | false
   ? never
-  : SWRKey extends infer Arg
+  : SWRKey extends string | infer Arg
```
Comment (promer94) [inline _internal/types.ts:24]: why add string here ?

**Review by promer94 — APPROVED** [review]

File: _internal/types.ts (hunk 1 above)
Comment (huozhi) [reply _internal/types.ts:24]: good catch, accidentally

**Comment by BoneTM** [comment]
why the `useSWRInfinite` dont impl this stuff?

**Comment by JordanHoffman** [comment]
Sorry I'm still having this problem, I think it's maybe because of generic types or something?

I specified my fetcher function like this:
image

And then in my code it still shows as possibly undefined when doing the hooks:
image

Is it perhaps because doing useSWRImmutable<BuildPageConfig[]> took priority for the returned data type? Is there another way to fix this? i get confused pretty quickly with types.
