### PR TITLE
Fix race condition when calling mutate synchronously

### LINKED ISSUE #566: Race condition when mutate is called multiple times in short succession with the same key
# Bug report

First off, thank you for your awesome work on this library 😊  I really enjoy using it and it's tremendously helpful.

## Description / Observed Behavior

Calling mutate multiple times with the same key within a very short amount of time leads to a race condition. When I pass a callback function to mutate, if I update the value on call #1 of mutate, call #2 of mutate doesn't get the updated value.

This leads to weird unexpected bugs since it's not clear that the library will behave this way.

It seems like the bug is here: https://github.com/vercel/swr/blob/master/src/use-swr.ts#L131. If mutate is called multiple times in short succession, cache.get(key) will not be up to date.

## Expected Behavior

I expect no race condition. When I update the value on call #1 of mutate, I expect the value to be updated on call #2 of mutate.

## Repro Steps / Code Example

https://codesandbox.io/s/swr-mutate-race-condition-gnrs3

## Additional Context

SWR version: 0.2.3

### PR DESCRIPTION
**Pull request by shuding**
### Bug

We have this inconsistency issue in current version:

```js
// we call `mutate` twice, synchronously, with a callback that reads the latest value
// let's assume the initial data is `0`

mutate('key', v => v + 1, false)
mutate('key', v => v + 1, false)
```

The data should be `2` after these 2 synchronous mutation calls. However if you test, it is actually `1` (here's a great [bug reproduction](https://codesandbox.io/s/swr-mutate-race-condition-gnrs3) from @derindutz).

The cause is that we are always updating the cache in async (as #619 tries to fix), so the argument `v` passed to the second mutation callback is still `0`. To make it clear, here's a diagram addressing this bug:

image

### Solution

We at first [tried](https://github.com/vercel/swr/pull/619/files#diff-755ef1ecc6f2f4c1cc601c6091dfcba5f674c653863b70913a115c0856a7b632R141) to make the mutate process synchronous (if the callback is not a promise or async function), but that brings another issue which is intermediate state:

```js
mutate('key', v => v + 1, false)
mutate('key', v => v + 1, false)
```

Now it correctly renders `2` at the end, but there's a moment that `1` was rendered before that. Instead we should "batch" 
synchronous mutations. It is because that the first mutation can't get deduplicated by the second one anymore. They both render the data.

image

To ensure the **correctness** of `mutate`, we need to make state broadcasting always asynchronous (kinda like React), but cache needs to be updated ASAP. So the latter mutations will always have the result from the former, but only the last mutation will get rendered:

image

The consequence of this fix is, if you mutate something and immediately check the result, it won't be updated. So in our test I added `await 0` to delay the check in the next tick:

```js
mutate('mutate-3', 'off', false)
await 0 // if no `await` here, it's gonna be wrong
expect(container.textContent).toMatchInlineSnapshot(`"off"`)
```

Fixes #566. Related to #619.

### CODE REVIEW

File: src/use-swr.ts [hunk 1]
```diff
@@ -45,6 +45,12 @@ const CACHE_REVALIDATORS = {}
 const MUTATION_TS = {}
 const MUTATION_END_TS = {}
 
+// generate strictly increasing timestamps
+let now = (() => {
```
Comment (huozhi) [inline src/use-swr.ts:49]:
```suggestion
const now = (() => {
```

File: src/use-swr.ts [hunk 2]
```diff
@@ -122,28 +128,32 @@ const mutate: mutateInterface = async (
...
+  MUTATION_TS[key] = now() - 1
   MUTATION_END_TS[key] = 0
 
-  // keep track of timestamps before await asynchronously
+  // track timestamps before await asynchronously
   const beforeMutationTs = MUTATION_TS[key]
   const beforeConcurrentPromisesTs = CONCURRENT_PROMISES_TS[key]
 
   let data, error
+  let isMutationAsync = false
```
Comment (huozhi) [inline src/use-swr.ts:143]: maybe isMutationAsync -> isAsyncMutation? (not blocking)

File: src/use-swr.ts [hunk 3]
```diff
@@ -163,13 +174,31 @@ const mutate: mutateInterface = async (
...
+  MUTATION_END_TS[key] = now() - 1
+
+  if (!isMutationAsync) {
+    // let's always broadcast in the next tick
+    // to dedupe synchronous mutation calls
+    // check out https://github.com/vercel/swr/pull/735 for more details
+    await 0
+
+    // we skip broadcasting if there's another mutation
+    // happened synchronously
```
Comment (huozhi) [inline src/use-swr.ts:193]: seems are same code with above, maybe we can make it a short function? like

```js
const resolveDataOnMutation = () => {
  if (
      beforeMutationTs !== MUTATION_TS[key] ||
      beforeConcurrentPromisesTs !== CONCURRENT_PROMISES_TS[key]
    ) {
      if (error) throw error
      return data
    }
  }
}
```

you might come up with other better names

**Comment by shuding** [comment]
Great feedback @huozhi, thanks!

**Review by huozhi — APPROVED** [review]
LGTM! awesome work and explanation there 👍

File: src/use-swr.ts [hunk 4]
```diff
@@ -122,28 +128,32 @@ const mutate: mutateInterface = async (
...
   const beforeConcurrentPromisesTs = CONCURRENT_PROMISES_TS[key]
 
   let data, error
+  let isAsyncMutation = false
 
   if (_data && typeof _data === 'function') {
     // `_data` is a function, call it passing current cache value
     try {
-      data = await _data(cache.get(key))
+      _data = _data(cache.get(key))
```
Comment (promer94) [inline src/use-swr.ts:148]: we can keep the previous 'else if' flow here instead of reassign _data here ?
```js
if (_data && typeof _data === 'function') {
    // `_data` is a function, call it passing current cache value
    try {
      data = _data(cache.get(key))
    } catch (err) {
      error = err
    }
  } else if (_data && typeof _data.then === 'function') {
    // `_data` is a promise
    isAsyncMutation = true
    try {
      data = await _data
    } catch (err) {
      error = err
    }
  } else {
    data = _data
  }
```

Comment (shuding) [reply src/use-swr.ts:148]: We can’t. If `_data` is an async function, calling it without `await` will get a promise returned, and we have to resolve it again.

Comment (promer94) [reply src/use-swr.ts:148]: On i see now 😅. I think i can add a test for mutate with async function. we don't have one now.

Comment (shuding) [reply src/use-swr.ts:148]: @promer94 that would be great, thanks!

**Comment by shuding** [comment]
Tested a bit, should be fine to ship this :)
