### PR TITLE
fix: Invalidate the key when mutating without revalidating

### LINKED ISSUE #828: Clear dedupingInterval of an unmounted key
# Bug report

## Description

I am developing a simple _CRUD_ application with two views:

_App.jsx_
```jsx
<Route path="/" component={User} />
<Route path="/edit" component={Edit} />
```
_User.jsx_
```jsx
const { data } = useSWR('/api/user', fetcher, { dedupingTime: 60000 });

return (
  <h1>{data.name}</h1>
)
```

_Edit.jsx_
```jsx
const editName = (name) => {
  fetch('/api/user/edit', { method: 'post', name })
  mutate('/api/user') // here User.jsx is unmounted
}

return (
  <button onClick={editName}>EDIT NAME</button>
)
```

If the user follows these steps:

- Navigate to '/'
- Navigate to '/edit'
- Click on edit name button
- Come back to '/' after 1 second

_/api/user_  data contains an old cached value.

I've tried to manually delete the cache value instead of calling _mutate_, but the issue remains.
_CONCURRENT_PROMISES_ remains fullfilled with the previous payload.

```js
const editName = (name) => {
  fetch('/api/user/edit', { method: 'post', name })
  cache.delete('/api/user')
}
```

## Expected Behavior

After calling _mutate_ on _Edit.jsx,_ I expect that a revalidation occurs when _User.jsx_ is mounted, ignoring _dedupingInterval_ value.
In other words, dedupingInterval should be cleared if mutate is called on an unmounted key.

### PR DESCRIPTION
**Pull request by shuding**
Fixes #828, closes #1139.

There're some scenarios that a revalidation **won't** happen when mutating a key:
- When `mutate(key)` but there is no mounted `useSWR(key)` hook. A revalidation might not happen after mounting hook if it's still within the dedupling interval.
- When `mutate(key, data)` but there is no mounted `useSWR(key)` hook. Same reason as above.

When it doesn't revalidate immediately, it should skip deduplication until the next revalidation time. This PR fixes the bug.

Worth mentioning that the fix was originally proposed by @MoonBall, thank you!

### CODE REVIEW

File: src/use-swr.ts [hunk 1]
```diff
@@ -262,7 +261,8 @@ export const useSWRHandler = <Data = any, Error = any>(
           broadcastState(cache, key, newData, newState.error, false)
         }
       } catch (err) {
-        cleanupState()
+        // Reset the state immediately.
+        cleanupState(startAt!)
```
Comment (huozhi) [inline src/use-swr.ts:265]: Maybe give startAt a default value -1 or disable the lint rule `Forbidden non-null assertion`

Comment (shuding) [reply src/use-swr.ts:265]: Sure!

Comment (shuding) [reply src/use-swr.ts]: I decided to disable that line only since the rule is overall helpful.

**Review by huozhi — APPROVED** [review]
