### PR TITLE
Refine createCache

### LINKED ISSUE #1275: createCache with revalidateOnFocus does not work
# Bug report

## Description / Observed Behavior
Custom cache settings in `1.0.0-beta.8` disables `revalidateOnFocus` behaviour; `focus` and `visibilitychange` events are not revalidating SWR caches.

## Expected Behavior
Revalidate on focus on `revalidateOnFocus: true`, as non-cache version does.

## Repro Steps / Code Example
CodePen: https://codepen.io/origin-master/pen/WNjwgYy

## Additional Context
SWR version: 1.0.0-beta.8

## This can be a problem...
`registerOnFocus` called in only here, and it's based on `defaultConfig.cache`:

https://github.com/vercel/swr/blob/c677d042c1307e00c641a2fbe8b559a1413670b5/src/use-swr.ts#L49-L62

Current API encourages only `cache` from `createCache(...)` should be put into `SWRConfig`, and doesn't cares `mutate`:
```js
const { cache, mutate } = createCache(new Map());
const Config = () => <SWRConfig value={{ cache }} />
```

### PR DESCRIPTION
**Pull request by huozhi**
Fixes #1275

### Changes

* Only need to `setupOn<Event>` for cache
* Setup global listeners inside `createCache` 

```js
createCache(new Map(), {
  // if you want to override any event that can trigger revalidation, use following options

  // override default behavior of revalidate on focus, it will revalidate on your own `focus` event now
  setupOnFocus(focusRevalidator) {
      customEvent.on('focus', focusRevalidator)
   },

   // override default behavior of revalidate on reconnect, it will revalidate on custom network events now
   setupOnReconnect(reconnectRevalidator) {
     customEvent.on('reconnect', reconnectRevalidator)
   }
})
```

### Fixes

* Fix custom cache is not bound to env like `focus`, `reconnect` events on web

### CODE REVIEW

File: src/types.ts [hunk 1]
```diff
@@ -49,8 +49,8 @@ export interface Configuration<
 
   isOnline: () => boolean
   isDocumentVisible: () => boolean
-  registerOnFocus: (cb: () => void) => void
-  registerOnReconnect: (cb: () => void) => void
+  attachOnFocus: (cb: () => void) => () => void
```
Comment (shuding) [inline src/types.ts:52]: We can rename them to `setupOnFocus`, also more intuitive I guess?

File: src/use-swr.ts [hunk 2]
```diff
@@ -488,6 +497,10 @@ export function useSWRHandler<Data = any, Error = any>(
     configRef.current = config
   })
 
+  useIsomorphicLayoutEffect(() => {
```
Comment (shuding) [inline src/use-swr.ts:500]: This will cause the listeners being added by every `useSWR` hook. I think we should add the setup/teardown logic in `SWRConfig`.

**Review by shuding — CHANGES_REQUESTED** [review]

File: src/use-swr.ts (hunk 2 above)
Comment (huozhi) [reply src/use-swr.ts:500]: yes but we're allowed user to pass `cache` per hook, that would also be a inconsistent

File: src/use-swr.ts [hunk 3]
```diff
@@ -45,22 +45,31 @@ const getGlobalState = (cache: Cache) => {
...
-// Setup DOM events listeners for `focus` and `reconnect` actions
-if (!IS_SERVER) {
+function attachGlobalEvents(config: Configuration) {
   const [FOCUS_REVALIDATORS, RECONNECT_REVALIDATORS] = getGlobalState(
-    defaultConfig.cache
+    config.cache
   )
   const revalidate = (revalidators: Record<string, Revalidator[]>) => {
-    if (!defaultConfig.isDocumentVisible() || !defaultConfig.isOnline()) return
+    if (!config.isDocumentVisible() || !config.isOnline()) return
```
Comment (huozhi) [inline src/use-swr.ts:53]: If we don't have these 2 conditions, it will be easy to put `attachGlobalEvents` inside `createCache`...

File: test/use-swr-focus.test.tsx [hunk 4]
```diff
@@ -200,4 +200,30 @@ describe('useSWR - focus', () => {
     await focusWindow()
     await screen.findByText('data: 5')
   })
+
+  it('should revalidate on focus even with custom cache', async () => {
+    let value = 0
+    const { cache } = createCache(new Map())
+
+    function Page() {
+      const { data } = useSWR('revalidaOnFocus + cache', () => value++, {
```
Comment (origin-master) [inline test/use-swr-focus.test.tsx:209]:
```suggestion
      const { data } = useSWR('revalidateOnFocus + cache', () => value++, {
```
typo here

File: src/use-swr.ts [hunk 5]
```diff
@@ -45,22 +45,31 @@ const getGlobalState = (cache: Cache) => {
...
-  defaultConfig.registerOnFocus(() => revalidate(FOCUS_REVALIDATORS))
-  defaultConfig.registerOnReconnect(() => revalidate(RECONNECT_REVALIDATORS))
+  const onFocus = () => revalidate(FOCUS_REVALIDATORS)
+  const onReconnect = () => revalidate(RECONNECT_REVALIDATORS)
+  const dettachOnFoucs = config.attachOnFocus(onFocus)
+  const dettachOnReconnect = config.attachOnReconnect(onReconnect)
+
+  return () => {
+    dettachOnFoucs()
+    dettachOnReconnect()
```
Comment (origin-master) [inline src/use-swr.ts:66]:
```suggestion
  const detachOnFoucs = config.attachOnFocus(onFocus)
  const detachOnReconnect = config.attachOnReconnect(onReconnect)

  return () => {
    detachOnFoucs()
    detachOnReconnect()
```
typo here

File: src/use-swr.ts (hunk 2 above)
Comment (shuding) [reply src/use-swr.ts:500]: Oh you're right... :sadparrot: then maybe it's not a good idea to allow per hook cache?

Comment (huozhi) [reply src/use-swr.ts:500]: @shuding I think we need to figure out here what we want to support for global events revalidation, there will be ways to achieve : )
I'll call `config.isDocumentVisible` and `config.isOnline` as `env cond` (environment condition) in the following sections.


We have these combinations
* default cache + default env  ✅
* default cache + custom env❓
* custom cache + default env ❓
* custom cache + custom env ❓

If a hook has customized **env cond**, the global one will still do the routine. Each cache just need to be setup once with default **env cond** or customized **env cond**.

Support default **env cond**: WeakSet to count if the custom cache is existed, setup for it only once;
Support customized **env cond**: This only occurs in `SWRConfig`, setup once for each `SWRConfig`;

IMO, ideally the **env cond** won't change frequently, WeakSet can be an option cause you may have few `SWRConfig` with different cache but same **env cond**

File: src/use-swr.ts [hunk 6]
```diff
@@ -45,22 +45,31 @@ const getGlobalState = (cache: Cache) => {
...
 
     for (const key in revalidators) {
       if (revalidators[key][0]) revalidators[key][0]()
     }
   }
-  defaultConfig.registerOnFocus(() => revalidate(FOCUS_REVALIDATORS))
-  defaultConfig.registerOnReconnect(() => revalidate(RECONNECT_REVALIDATORS))
+  const onFocus = () => revalidate(FOCUS_REVALIDATORS)
+  const onReconnect = () => revalidate(RECONNECT_REVALIDATORS)
+  const teardownOnFoucs = config.setupOnFocus(onFocus)
```
Comment (origin-master) [inline src/use-swr.ts:61]:
```suggestion
  const teardownOnFocus = config.setupOnFocus(onFocus)
```
more typo

File: src/use-swr.ts (hunk 2 above)
Comment (shuding) [reply src/use-swr.ts:500]: OK I think we should think about the most common use case: 99% apps only have 1 environment. So it's a good restriction that you shouldn't have per-hook, custom `isOnline` config, etc (they're safe to be singletons). 

Since we still haven't officially documented env settings, a good approach is to move those env settings into `createCache` (e.g. `createCache(provider, { isOnline, isDocumentVisible })`), so we can directly set up event listeners there too, before React's runtime.

File: src/utils/web-preset.ts [hunk 7]
```diff
@@ -9,52 +10,66 @@ import { isUndefined } from './helper'
...
-    addDocumentEventListener('visibilitychange', cb)
-    addWindowEventListener('focus', cb)
+const setupOnFocus = (cb: () => void) => {
+  // focus revalidate
+  documentEventListener(add)('visibilitychange', cb)
+  windowEventListener(add)('focus', cb)
+  return () => {
+    documentEventListener(remove)('visibilitychange', cb)
+    windowEventListener(remove)('focus', cb)
   }
```
Comment (shuding) [inline src/utils/web-preset.ts:45]: If we are setting up those listeners globally instead of doing it with a hook, there's no need to return unregisters I think.

File: src/utils/web-preset.ts [hunk 8]
```diff
@@ -9,52 +10,66 @@ import { isUndefined } from './helper'
...
+  windowEventListener(add)('online', onOnline)
+  // nothing to revalidate, just update the status
+  windowEventListener(add)('offline', onOffline)
 
-    // nothing to revalidate, just update the status
-    addWindowEventListener('offline', () => (online = false))
+  return () => {
+    windowEventListener(remove)('online', onOnline)
+    windowEventListener(remove)('offline', onOffline)
   }
```
Comment (shuding) [inline src/utils/web-preset.ts:64]: Same as above.

File: src/use-swr.ts [hunk 9]
```diff
@@ -45,22 +47,23 @@ const getGlobalState = (cache: Cache) => {
   ]
 }
 
-// Setup DOM events listeners for `focus` and `reconnect` actions
-if (!IS_SERVER) {
-  const [FOCUS_REVALIDATORS, RECONNECT_REVALIDATORS] = getGlobalState(
-    defaultConfig.cache
-  )
+function setupGlobalEvents(cache: Cache, _provider: Partial<Provider> = {}) {
```
Comment (shuding) [inline src/use-swr.ts:50]: It seems that we are not using the second argument, what will the use case be link?

**Comment by shuding** [comment]
I pushed a change due to one comment ☝️ , let me know what do you think!

**Comment by huozhi** [comment]
force pushed it but honored your changes @shuding 
also add 2 test cases to cover the core changes

File: src/utils/web-preset.ts [hunk 10]
```diff
@@ -9,52 +10,49 @@ import { isUndefined } from './helper'
...
-  typeof document !== 'undefined'
-    ? document.addEventListener.bind(document)
-    : null
+const hasWindow = typeof window !== 'undefined'
+const hasDocument = typeof document !== 'undefined'
+
+// For node and React Native, `add/removeEventListener` doesn't exist on window.
+const onWindowEvent =
+  hasWindow && !isUndefined(window[ADD]) ? window[ADD].bind(window) : noop
+const onDocumentEvent = hasDocument ? document[ADD].bind(document) : noop
```
Comment (shuding) [inline src/utils/web-preset.ts:22]: I don't think we need to bind, since we are not using `this` in our callbacks. So we can make those simpler:

```js
const addWindowListener = typeof window !== 'undefined' && isUndefined(window[ADD]) ? window[ADD] : null

...

if (addWindowListener) addWindowListener('focus', cb)
```

Same for document listeners. So we can get rid of `noop` as well, make the bundle smaller.

Comment (huozhi) [reply src/utils/web-preset.ts:22]: removed `bind` calls. but keep the others change since they make the final bundle reduced 25bytes 😌

Comment (shuding) [reply src/utils/web-preset.ts:22]: I don't see your push somehow 🤔

Comment (huozhi) [reply src/utils/web-preset.ts]: updated

**Review by shuding — APPROVED** [review]
