### PR TITLE
dispatch's payload type is actionType and run lint

### LINKED ISSUE #773: [tsc] Cannot find name 'Deno'.
# Bug report

## Description / Observed Behavior

`src/use-swr.ts:30:13 - error TS2304: Cannot find name 'Deno'.`

## Expected Behavior
Error not found.

## Repro Steps / Code Example

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context
Fork master branch and `yarn run types:check`

### PR DESCRIPTION
**Pull request by matamatanot**
close #773

When I started reading `use-swr.ts`, it was hard to imagine what arguments dispatch was receiving at first. I think it will be somewhat more readable.

Also, after `yarn run lint:fix`, a line break occurred around line 30.

### CODE REVIEW

File: src/use-swr.ts [hunk 1]
```diff
@@ -25,7 +25,9 @@ import {
 } from './types'
 
 // @ts-ignore
-const IS_SERVER = typeof window === 'undefined' || !!(typeof Deno !== 'undefined' && Deno && Deno.version && Deno.version.deno)
+const IS_SERVER =
+  typeof window === 'undefined' ||
+  !!(typeof Deno !== 'undefined' && Deno && Deno.version && Deno.version.deno)
```
Comment (shuding) [inline src/use-swr.ts:30]: To make the tests pass, you need to move that `// @ts-ignore` (line 28) here.

**Review by shuding — APPROVED** [review]
