### PR TITLE
enhance: move online listeners to config (#474)

### LINKED ISSUE #474: Move the `online` event listener to config
# Bug report

## Description / Observed Behavior

SWR registers multiple `online` event listeners:

image

## Expected Behavior

There should be only 1 listener, just like `visibilitychange`.

## Additional Context

https://github.com/vercel/swr/blob/03c7b8320dde30fab24c9706cd33c5eb27d0552e/src/use-swr.ts#L494-L497

needs to be moved to

https://github.com/vercel/swr/blob/03c7b8320dde30fab24c9706cd33c5eb27d0552e/src/config.ts#L87-L88

### PR DESCRIPTION
**Pull request by huozhi**
## Changes

Resolves #474 , attach online event listeners in config 

## Test Plan

* build swr locally and yarn link to the examples/focus-revalidate 
* add one more swr hook there
* disconnect and reconnect the network in devtools
* expected: the requests get re-fetched

### CODE REVIEW

File: src/config.ts [hunk 1]
```diff
@@ -75,25 +76,44 @@ const defaultConfig: ConfigInterface = {
...
+    window.addEventListener('visibilitychange', revalidate, false)
+    window.addEventListener('focus', revalidate, false)
+
+    focusEventsBinded = true
+  }
+
+  // set up reconnecting when the browser regains network connection
+  if (defaultConfig.revalidateOnReconnect && !onlineEventsBinded) {
+    const revalidate = () => {
+      if (!isOnline()) return
```
Comment (huozhi) [inline src/config.ts:100]: I don't know if we need `isDocumentVisible` condition here, so I left a comment for checking.

File: src/use-swr.ts [hunk 2]
```diff
@@ -513,6 +518,14 @@ function useSWR<Data = any, Error = any>(
           revalidators.pop()
         }
       }
+      if (onReconnect && RECONNECT_REVALIDATORS[key]) {
```
Comment (huozhi) [inline src/use-swr.ts:521]: the recycle revalidator part is kind of repetitive, we can re-abstract them but I feel it would be good in the separate PR

File: src/config.ts [hunk 3]
```diff
@@ -75,25 +76,44 @@ const defaultConfig: ConfigInterface = {
...
 
 // Focus revalidate
-let eventsBinded = false
-if (typeof window !== 'undefined' && window.addEventListener && !eventsBinded) {
-  const revalidate = () => {
-    if (!isDocumentVisible() || !isOnline()) return
+if (typeof window !== 'undefined' && window.addEventListener) {
+  // only bind the events once
+  let focusEventsBinded = false
+  let onlineEventsBinded = false
```
Comment (shuding) [inline src/config.ts:82]: This logic can be removed.

**Comment by huozhi** [comment]
> I think we don't need the extra `RECONNECT_REVALIDATORS` 🤔. Can we use the same `FOCUS_REVALIDATORS` (and rename it to just `REVALIDATORS`?

we still have `CACHE_REVALIDATORS` and it works in a different way, i guess they might not able to merge 3 of them together? if revalidators for "focus" and "reconnect" are megerable, do you feel ok to call it "ONLINE_FOCUS_REVALIDATORS"? or any other better ideas about it?

**Comment by huozhi** [comment]
oops, looks like if we still have to separate reconnect and focus revalidators? when you disable `revalidateOnFocus`, first callback in `FOCUS_REVALITORS` still get executed even it's actually the one for reconnect

File: src/use-swr.ts [hunk 4]
```diff
@@ -507,41 +559,16 @@ function useSWR<Data = any, Error = any>(
       CACHE_REVALIDATORS[key].push(onUpdate)
     }
```
Comment (shuding) [inline src/use-swr.ts:560]: We can move https://github.com/vercel/swr/pull/476/files#diff-ab20307c185620c9b54994fa4dcee1b7R512-R513 here and change https://github.com/vercel/swr/pull/476/files#diff-ab20307c185620c9b54994fa4dcee1b7R556-R560 to

```js
addRevalidator(RECONNECT_REVALIDATORS, onUpdate)
```
