### PR TITLE
breaking: Throw error when using suspense on the server side without fallback in React 18

### LINKED ISSUE #1832: SWR should throw when trying to suspend on the server
# Bug report

## Description / Observed Behavior

Server-side streaming with useSWR appears to work, in that you can see the data fetched on the server and sent through script tags later on. However, it isn't currently set up to share data between the server and client, causing a client-side fetch to happen in addition to the server-side fetch. Since nothing breaks or warns, it looks like this is fully working when it's not.

## Expected Behavior

As suggested by @devknoll [here](https://twitter.com/devknoll/status/1487588880299831302), useSWR should throw a friendly error when the the `suspense` flag is on and it tries to suspend on the server, so folks know this isn't yet implemented fully. 

## Repro Steps / Code Example

1. Have the following code: 
index.js
```
<Suspense fallback={<div>Loading profile…</div>}>
    <Profile />
</Suspense>
```

profile.jsx
```
function Profile(props) {
   const data = useSWR(fetcher, '/some/profile', {suspense: true})
   return (
        <div> Profile ID: { data.id } </div>
   );
}

```
2. Turn on the `concurrentFeatures` flag.
3. Check the HTML response in the network tab and see the script tags being sent from the server with the data.
3. See that there are also client-side fetches for the same data in the network tab.

### PR DESCRIPTION
**Pull request by shuding**
Close #1841, close #1832. 

More discussions can be found [here](https://github.com/vercel/swr/issues/1906). In short, libraries like SWR should not support fetching data on the server side as of today.

### CODE REVIEW

File: src/use-swr.ts [hunk 1]
```diff
@@ -542,6 +547,15 @@ export const useSWRHandler = <Data = any, Error = any>(
   // If there is no `error`, the `revalidation` promise needs to be thrown to
   // the suspense boundary.
   if (suspense && isUndefined(data) && key) {
+    // SWR should throw when trying to use Suspense on the server with React 18,
+    // without providing any initial data. See:
+    // https://github.com/vercel/swr/issues/1832
+    if (!IS_REACT_LEGACY && IS_SERVER) {
```
Comment (huozhi) [inline src/use-swr.ts:553]: should we throw whatever data and key is?

Comment (shuding) [reply src/use-swr.ts:553]: @huozhi As the comment and discussions mentioned, we should only throw **if we are going to** suspend on the server side.

**Review by huozhi — APPROVED** [review]

File: src/use-swr.ts [hunk 2]
```diff
@@ -542,6 +547,15 @@ export const useSWRHandler = <Data = any, Error = any>(
...
+      throw new Error(
+        'Fallback data is required to use suspense on the server side.'
```
Comment (shuding) [inline src/use-swr.ts:555]:
```suggestion
        'Fallback data is required when using suspense in SSR.'
```
