### PR TITLE
Fix: raf return type

### LINKED ISSUE #2073: vite build types error
image vite 
Error while building

**node_modules/swr/_internal/dist/_internal/utils/env.d.ts:4:76 - error TS2694: Namespace 'global.NodeJS' has no exported member 'Timeout'.

4 export declare const rAF: (f: (...args: any[]) => void) => number | NodeJS.Timeout;**

### PR DESCRIPTION
**Pull request by huozhi**
Fixes #2073

### CODE REVIEW

File: _internal/utils/env.ts [hunk 1]
```diff
@@ -6,7 +6,9 @@ export const IS_REACT_LEGACY = !React.useId
 export const IS_SERVER = !isWindowDefined || 'Deno' in window
 
 // Polyfill requestAnimationFrame
-export const rAF = (f: (...args: any[]) => void) =>
+export const rAF = (
+  f: (...args: any[]) => void
+): number | ReturnType<typeof setTimeout> =>
```
Comment (promer94) [inline _internal/utils/env.ts:11]:
```suggestion
export const rAF: (f: (...args: any[]) => any) => any = (f) =>
  hasRequestAnimationFrame()
    ? window['requestAnimationFrame'](f)
    : setTimeout(f, 1)
```
Since it's just a internal function. Let's keep it simple.

**Review by promer94 — CHANGES_REQUESTED** [review]

File: _internal/utils/env.ts (hunk 1 above)
Comment (huozhi) [reply _internal/utils/env.ts:11]: it doesn't hurt to give the explict type, and I feel it's simpler

**Review by promer94 — APPROVED** [review]
